const Event = use("Event");

Event.on("user::register", "Register.store");
Event.on("user::notify", "Register.notify");
Event.on("user::notifyReseler", "User.notifyReseler");
Event.on("user::notifyBlockedAccount", "User.notifyBlockedAccount");
Event.on("password::email", "PasswordEmail.store");
Event.on("password::changed", "PasswordChanged.store");
Event.on("contact::store", "Contact.store");
Event.on("contact::notify", "Contact.notify");
Event.on("newsletter::store", "Newsletter.store");
Event.on("newsletter::notify", "Newsletter.notify");
Event.on("order::storeWithdrawInHands", "Order.storeWithdrawInHands");
Event.on("order::notifyWithdrawInHands", "Order.notifyWithdrawInHands");
Event.on("order::approved", "Order.orderApproved");
Event.on("order::canceled", "Order.orderCanceled");
Event.on("order::storeBillet", "Order.storeBillet");
Event.on("order::storeCreditCard", "Order.storeCreditCard");
Event.on("order::notifyBillet", "Order.notifyBillet");
Event.on("order::notifyApproved", "Order.notifyApproved");
Event.on("order::notifyCanceled", "Order.notifyCanceled");
Event.on("order::tracking", "Order.tracking");
